### ISSUE TITLE
cannot edit User.sublime-settings

### ISSUE THREAD

**Issue by ucirello** [alvarolm/GoGuru#16]
It loads the User.sublime-settings but I cannot edit it. It seems it is locked into some read-only mode.

ST3 build 3112 - MacOS X

**Comment by alvarolm** [comment]
its fixed in version 0.1.5, sublime package control takes a while to pull the repo changes.
https://github.com/alvarolm/GoGuru/issues/13
https://github.com/alvarolm/GoGuru/pull/14
