### ISSUE TITLE
Cannot edit Default (OSX).sublime-keymap

### ISSUE THREAD

**Issue by ucirello** [alvarolm/GoGuru#17]
Same as #13

**Comment by alvarolm** [comment]
you should never edit the default files, edit the user files.

**Comment by ucirello** [comment]
Well, I just used the option from the menu. That's the file that's opened. I used the key bindings options, maybe an option is missing in the menu?

**Comment by alvarolm** [comment]
menu > preferences > package settings > GoGuru > Settings - User
or
cmd+shift+p and then type "GoGuru User Settings"

**but the file and the parent directory needs to be manually created**,
to fix this i just pushed version 0.1.7.

**I recommend you to first delete the current GoGuru package using the sublime package control and wait for the version 0.1.7 to be available at the package control repo, (check here https://packagecontrol.io/packages/GoGuru under Details > version) then install it again.**

sorry for the trouble

**Comment by alvarolm** [comment]
I never gave you a response about the keybindigs, sorry for that :(

you can set your custom keybindigs at:

**Preferences > Key Bindings - User**

that file stores all your custom keybinds (overriding the defaults), including from other plugins, so its a good idea to keep all organized with comments, groups and so on.
