### ISSUE TITLE
Guru commands never return

### ISSUE THREAD

**Issue by britt** [alvarolm/GoGuru#26]
I installed the GoGuru plugin using package control and the guru command. I ran a few commands in GoGuru and everything worked fine. Then for other reasons I restarted Sublime Text and now it says it's running the guru command but it never terminates and I never get any output.

```
Running guru callers command...
```

This is likely a problem with my installation, but have you seen this before?

**Comment by alvarolm** [comment]
most likely an unhandled exception occurred after the command was executed, open the sublime console and take a look at the lines that start with GoGuru

**Comment by alvarolm** [comment]
https://github.com/alvarolm/GoGuru/issues/18#issuecomment-222284301

**Comment by britt** [comment]
Thanks, it turns out Sublime just wasn't picking up GOPATH.
