### ISSUE TITLE
caller cmd only finds callers in same package 

### ISSUE THREAD

**Issue by ltzmaxwell** [alvarolm/GoGuru#27]
No callers in other packages were found.

**Comment by ltzmaxwell** [comment]
I tried to set scope , not working still

**Comment by alvarolm** [comment]
can you please post the debug logs ? https://github.com/alvarolm/GoGuru/issues/18#issuecomment-222284301

**Comment by ltzmaxwell** [comment]
Package Control: No updated packages
GoGuru [ERROR]: ('guru: analysis scope has no main and no tests\n',)

**Comment by ltzmaxwell** [comment]
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings":
    {
        "GoGuru": {
            "guru_scope": ["github.com/guru"],
            "output": "output_panel"
        }
    },
}
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings":
    {
        "GoGuru": {
            "guru_scope": ["github.com/guru"],
            "output": "output_panel"
        }
    },
}

**Comment by alvarolm** [comment]
there you have it:

> GoGuru [ERROR]: ('guru: analysis scope has no main and no tests\n',)

besides make sure that the cursor is over the identifier u wan to query (variable, constant...)

**Comment by ltzmaxwell** [comment]
Yeah , Im sure about it .

**Comment by ltzmaxwell** [comment]
I hava a main package , and  a test package , try to find caller from testFunc in test package, and that the calller should be in main package.
but It give the error above.

**Comment by ChrisHines** [comment]
The config posted above has the `guru_scope` set incorrectly. It should refer to the package you want to analyze, the main package and/or the package with tests.
