### ISSUE TITLE
no initial packages were loaded [improve local_package detection]

### ISSUE THREAD

**Issue by jackyzhao001** [alvarolm/GoGuru#28]
hello:
when i used GoGuru .The following is an error message
open x:\xxx|xxx|xxx: The system cannot find the path specified.
guru: no initial packages were loaded

what should i do

thanks.

**Comment by wanjm** [comment]
come accross the same problem; which tells ;

open /git/tokencontrol/src/provider/wx: no such file or directory
guru: no initial packages were loaded

but /git/tokencontrol/src/provider/wx should be /home/test/git/tokencontrol/src/provider/wx

why guru try to open the wrong directory;

when I try to ln -s /home/test/git /git;
it seems open file success, but more error comes; guru doesn't get the correct GOPATH enivironment value ( which is different from what I set, missing some directorys"

**Comment by wanjm** [comment]
I finally make it work
but some problem found:
1.goguru_use_current_package doesn't work in configure file, it is always Ture in guru debug log;
2. plugin can't correctly deal $GOPATH. 
   in the debug log, the GOPATH is change from the $GOPATH to  $GOPATH/src;  so when the GOPATH in ENV has ":"  then it will not work any more;
3. to solve 2, I can only set the
 "goguru_env": {"GOPATH":"path to my own project"},
4. set 
    "goguru_scope": ["my main package"],

**Comment by anacrolix** [comment]
I get this when I use GoGuru on a standard library package. It infers 'local_package' = '../../src/go/src/net/http', which results in
open /Users/anacrolix/gopath/src/github.com/anacrolix/torrent/src/go/src/net/http: no such file or directory
guru: couldn't load packages due to errors: ../../src/go/src/net/http
