### ISSUE TITLE
goguru "definition" could jump straight to the definition

### ISSUE THREAD

**Issue by ucirello** [alvarolm/GoGuru#3]
Feature request.

When calling goguru definition, instead of return goguru's output, it could jump straight to the file with the definition.

**Comment by alvarolm** [comment]
done!, needs "jumpto_definition" set to true.

https://github.com/alvarolm/GoGuru/commit/f6f926f0d0543bf3dbd2e47bbc52065dfeb36b22
https://github.com/alvarolm/GoGuru/commit/f6f926f0d0543bf3dbd2e47bbc52065dfeb36b22
https://github.com/alvarolm/GoGuru/commit/df625024d7c9bf846a6e834841b50483311483b5

be sure to update to the latest version & tell me what u think :)

**Comment by ucirello** [comment]
works

**Comment by arsham** [comment]
It's perfect. Is it possible to assign it to a mouse action? I would like to add the following to **Default (Linux).sublime-mousemap** file:

```json
{
    "button": "button2",
    "modifiers": ["ctrl"],
    "command": "goguru_jumpto_definition",
    "press_command": "drag_select",
    "context": [
        {
            "key": "selector",
            "operator": "not_equal",
            "operand": "source.go",
            "match_all": true,
        }
    ]
}
```

Thank you.
