### ISSUE TITLE
Can't edit Key bindings

### ISSUE THREAD

**Issue by mwf** [alvarolm/GoGuru#35]
Mac OS X 10.11.6
Sublime 3126 (latest stable)

I can't edit key binding file - it shows an error `Unable to open /Users/mwf/Library/Application Support/Sublime Text 3/Packages/GoGuru/Default (OSX).sublime-keymap`

There is really no such file - not even "GoGuru" dir under packages. But it opens the file somehow in read-only mode - don't know where it takes from. 
Maybe from the package source file - `/Users/mwf/Library/Application Support/Sublime Text 3/Installed Packages/GoGuru.sublime-package`

Please check if the package installation works well and the package is unpacked to Packages/GoGuru

**Comment by alvarolm** [comment]
mate, I believe you should edit your **User key bindings** to override the plugin defaults, you should never edit the other keybindings as far as I know.

http://docs.sublimetext.info/en/latest/customization/key_bindings.html#defining-and-overriding-key-bindings

Have a great day !  ;)
