### ISSUE TITLE
callers , callees, peers, callstack just doesn't work in Emacs

### ISSUE THREAD

**Issue by xueyouchao** [alvarolm/GoGuru#38]
These four functions just give me lots of useless errors which have nothing to do with the function I am inspecting.
<img width="1439" alt="screen shot 2017-08-18 at 12 52 30 am" src="https://user-images.githubusercontent.com/281414/29444725-f1b91500-83af-11e7-888d-b1f4c5aaee83.png">

**Comment by alvarolm** [comment]
a the time this plugin only works with the sublime editor, I recommend you to take a look at the go-mode.el project (https://github.com/dominikh/go-mode.el) by @dominkh (https://github.com/dominikh/)
