### ISSUE TITLE
Leverage golangconfig for Go environment variables

### ISSUE THREAD

**Issue by allgeek** [alvarolm/GoGuru#4]
First, thanks for your efforts here - I've been looking forward to seeing adonovan's recent hard work on guru integrated into Sublime Text!  I'll play with this as soon as I have some time, but quick feedback after reviewing the install notes:

It looks like you are rolling your own mechanism for managing GOPATH etc.  I'd highly suggest trying to leverage the official [golangconfig](https://github.com/golang/sublime-config) dependency, that was recently added to help create a good ecosystem for Go-related packages in Sublime Text.  Then users only have to configure one set of things globally or per-project as appropriate, and this package, the [Golang Build](https://github.com/golang/sublime-build) package, and any other packages can make use of them.

**Comment by alvarolm** [comment]
done my friend!, you need to set "use_golangconfig" to true in your config in order to work, if you dont have 'golangconfig' installed it will fallback to the internal mechanism.

be sure to update to the latest version & please tell me what you think :)

**Comment by nsf** [comment]
Wanted to try golangconfig, I have a non-standard project GOPATH setup, but it appears to be broken, I think dependencies.json file is missing as described here: https://github.com/golang/sublime-config/blob/master/docs/package_developer.md#requiring-the-dependency. Just a guess, I know nothing about sublime package dependencies. That is if something else didn't install the golangconfig it won't be installed by GoGuru.

What I get in the console:

```
GoGuru [ERROR]: ('golangconfig:', (<class 'NameError'>, NameError("global name 'golangconfig' is not defined",), <traceback object at 0x7f11c0f7d440>))
```

**Comment by alvarolm** [comment]
check out config:

	// env overwrites the default shell environment vars
	// e.g "env": { "GOPATH": "$HOME/go/bin:$PATH" }
	// not used when goguru_use_golangconfig is set to true
	"goguru_env": {},
