### ISSUE TITLE
$GOPATH is not $GOPATH/bin

### ISSUE THREAD

**Issue by ryboe** [alvarolm/GoGuru#42]
```json
// env overwrites the default shell environment vars
// e.g "env": { "GOPATH": "$HOME/go/bin:$PATH" }
// not used when goguru_use_golangconfig is set to true
"goguru_env": {},
```
[These lines](https://github.com/alvarolm/GoGuru/blob/master/Default%20(copy).sublime-settings#L34-L36) from `Default.sublime-settings` are confusing. The `$GOPATH` env should not be set to `$HOME/go/bin`. `$GOPATH` is the _parent_ of the directory containing all the Go binaries.

**Comment by alvarolm** [comment]
thanks!
