### ISSUE TITLE
Post too soon?

### ISSUE THREAD

**Issue by davmaz** [alvarolm/GoGuru#5]
This is frustrating -- waiting for the package manager to "allow" this. I would have made the post once it was actually usable by the package manager. In other words, I really want it! 

Is there another way to install it w/o using package install?

**Comment by alvarolm** [comment]
my fault, I didn't know it would take this long to be added. :(

in the meantime you could download the plugin here https://github.com/alvarolm/GoGuru/releases/download/0.1.1/GoGuru-0.1.1.zip and do it manually:
just extract the 'GoGuru' folder to your 'sublime-text-3/Packages' directory and thats it :)

**Comment by alvarolm** [comment]
it is now ! :) https://packagecontrol.io/packages/GoGuru
