### ISSUE TITLE
sublime package manager

### ISSUE THREAD

**Issue by davmaz** [alvarolm/GoGuru#8]
When is this going to be available in Sublime? Why is it taking so long to get it into the manager? Is there another way to install it in Sublime without using the package manager?

**Comment by alvarolm** [comment]
sorry for the delay, you can track the status here https://github.com/wbond/package_control_channel/pull/5443

**Comment by alvarolm** [comment]
it is now :) https://packagecontrol.io/packages/GoGuru

**Comment by davmaz** [comment]
Thanks for the info. And yes, it's available, and I love it. Good work!
