### ISSUE TITLE
Navigating to results file and line broken on Windows.

### ISSUE THREAD

**Issue by ChrisHines** [alvarolm/GoGuru#9]
Fixing PR on the way.

**Comment by alvarolm** [comment]
thanks Chris !, Just one question, https://github.com/alvarolm/GoGuru/pull/10 doesn't brake the regex on other platforms (linux, osx ?)?

**Comment by ChrisHines** [comment]
Just confirmed that it works OSX. It should be fine on Linux as well. It just makes sure not to match a ':' in the path until after a ".go" file extension is found.

**Comment by alvarolm** [comment]
https://github.com/alvarolm/GoGuru/pull/10 merged, btw GoGuru recently has been added to the sublime text package control repository https://packagecontrol.io/packages/GoGuru within the hour this pr should be available for update as version 0.1.3, thanks again ! ;-)
